version: '3.6'

services:
  database:
    image: postgres:12.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - /var/lib/postgresql/data
  app:
    ports:
      - 3000:3000
    volumes:
      - .:/aplicacao
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - database
