version: '2.2'

services:
  database:
    image: postgres:12.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    ports:
      - 3000:3000
    volumes:
      - .:/aplicacao
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      database:
        condition: service_healthy
  nginx:
    build:
      context: ./
      dockerfile: ./prod/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
